spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  application:
    name: mercado-livro
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
  servlet:
    context-path: /mercado-livro
    encoding:
      charset: UTF-8
      force-response: true
