#Criando a tabela de cliente
CREATE TABLE customer (
    id BIGINT NOT NULL AUTO_INCREMENT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

#Comentando as colunas
ALTER TABLE customer COMMENT 'Tabela de cliente';
ALTER TABLE customer MODIFY COLUMN id BIGINT COMMENT 'identificador do cliente';
ALTER TABLE customer MODIFY COLUMN name VARCHAR(100) COMMENT 'Nome do cliente';
ALTER TABLE customer MODIFY COLUMN name VARCHAR(100) COMMENT 'Email do cliente';
